import { useCallback, useEffect, useState } from "react";
import exampleMachineConfig from "../config/machineConfig.example.json";

const CONFIG_KEYS = ["a", "b", "c", "d", "e"];
const BASELINE_CONFIG = "d";

const getMachineApiBaseUrl = (machine) => {
  if (!machine) return null;
  return machine.api_base_url || `http://${machine.public_ip}:5000`;
};

const randomSelect = (items) => {
  if (!items || items.length === 0) {
    throw new Error("Cannot select from an empty list.");
  }
  return items[Math.floor(Math.random() * items.length)];
};

/**
 * Coordinates the experimental condition shown by the UI.
 *
 * The original deployment loaded real cloud machine addresses from S3. For the
 * release version, this hook reads a placeholder local config. Researchers can
 * replace that loader with S3, a database, a provisioning API, or a static file
 * generated by their own infrastructure.
 */
export const useExperiment = () => {
  const [experimentPhase, setExperimentPhase] = useState("baseline");
  const [currentConfig, setCurrentConfig] = useState(BASELINE_CONFIG);
  const [currentMachine, setCurrentMachine] = useState(null);
  const [usedConfigs, setUsedConfigs] = useState([]);
  const [apiBaseUrl, setApiBaseUrl] = useState(null);
  const [experimentStartTime, setExperimentStartTime] = useState(null);
  const [totalConversations, setTotalConversations] = useState(0);
  const [machineConfig, setMachineConfig] = useState(null);
  const [configLoading, setConfigLoading] = useState(true);
  const [configError, setConfigError] = useState(null);
  const [baselineMessageCount, setBaselineMessageCount] = useState(0);
  const [currentChatMessageCount, setCurrentChatMessageCount] = useState(0);
  const [isTransitioning, setIsTransitioning] = useState(false);
  const [connectionStatus, setConnectionStatus] = useState("unknown");
  const [transitionError, setTransitionError] = useState(null);
  const [isTestMode, setIsTestMode] = useState(
    process.env.REACT_APP_UI_TEST_MODE === "true"
  );
  const [testModeConnectionLog, setTestModeConnectionLog] = useState([]);
  const [isReconnecting, setIsReconnecting] = useState(false);
  const [currentMachineIndex, setCurrentMachineIndex] = useState(0);

  const loadMachineConfig = useCallback(() => {
    try {
      setConfigLoading(true);
      setConfigError(null);
      setMachineConfig(exampleMachineConfig);
    } catch (error) {
      setConfigError(error.message);
    } finally {
      setConfigLoading(false);
    }
  }, []);

  useEffect(() => {
    loadMachineConfig();
  }, [loadMachineConfig]);

  const selectBaselineMachine = useCallback(() => {
    if (!machineConfig) return null;

    const baselineConfig = machineConfig.configs[BASELINE_CONFIG];
    const selectedMachineIndex = Math.floor(
      Math.random() * baselineConfig.instances.length
    );
    const selectedMachine = baselineConfig.instances[selectedMachineIndex];
    const selectedApiBaseUrl = getMachineApiBaseUrl(selectedMachine);

    setCurrentConfig(BASELINE_CONFIG);
    setCurrentMachine(selectedMachine);
    setCurrentMachineIndex(selectedMachineIndex);
    setApiBaseUrl(selectedApiBaseUrl);
    setExperimentPhase("baseline");

    return {
      config: BASELINE_CONFIG,
      machine: selectedMachine,
      apiBaseUrl: selectedApiBaseUrl,
      needsNewSession: false,
    };
  }, [machineConfig]);

  useEffect(() => {
    if (machineConfig && !configLoading && !configError && !currentMachine) {
      selectBaselineMachine();
    }
  }, [
    machineConfig,
    configLoading,
    configError,
    currentMachine,
    selectBaselineMachine,
  ]);

  const beginExperiment = useCallback(() => {
    setExperimentPhase("experiment");
    setExperimentStartTime(new Date().toISOString());
  }, []);

  const selectFirstExperimentConfig = () => {
    if (!machineConfig) return null;

    const selectedConfigKey = randomSelect(CONFIG_KEYS);
    const selectedConfig = machineConfig.configs[selectedConfigKey];
    const selectedMachineIndex = Math.floor(
      Math.random() * selectedConfig.instances.length
    );
    const selectedMachine = selectedConfig.instances[selectedMachineIndex];
    const selectedApiBaseUrl = getMachineApiBaseUrl(selectedMachine);

    setCurrentConfig(selectedConfigKey);
    setCurrentMachine(selectedMachine);
    setCurrentMachineIndex(selectedMachineIndex);
    setApiBaseUrl(selectedApiBaseUrl);
    setUsedConfigs([selectedConfigKey]);
    setTotalConversations(1);

    return {
      config: selectedConfigKey,
      machine: selectedMachine,
      apiBaseUrl: selectedApiBaseUrl,
      needsNewSession: true,
      experimentCompleted: false,
      configInfo: {
        name: selectedConfig.name,
        description: selectedConfig.description || selectedConfig.name,
      },
    };
  };

  const selectNextConfig = () => {
    if (!machineConfig || experimentPhase !== "experiment") return null;

    const availableConfigs = CONFIG_KEYS.filter(
      (config) => !usedConfigs.includes(config)
    );

    if (availableConfigs.length === 0) {
      setExperimentPhase("completed");
      return {
        config: null,
        machine: null,
        apiBaseUrl: null,
        needsNewSession: false,
        experimentCompleted: true,
      };
    }

    const selectedConfigKey = randomSelect(availableConfigs);
    const selectedConfig = machineConfig.configs[selectedConfigKey];
    const selectedMachineIndex = Math.floor(
      Math.random() * selectedConfig.instances.length
    );
    const selectedMachine = selectedConfig.instances[selectedMachineIndex];
    const selectedApiBaseUrl = getMachineApiBaseUrl(selectedMachine);

    setCurrentConfig(selectedConfigKey);
    setCurrentMachine(selectedMachine);
    setCurrentMachineIndex(selectedMachineIndex);
    setApiBaseUrl(selectedApiBaseUrl);
    setUsedConfigs((previous) => [...previous, selectedConfigKey]);
    setTotalConversations((previous) => previous + 1);

    return {
      config: selectedConfigKey,
      machine: selectedMachine,
      apiBaseUrl: selectedApiBaseUrl,
      needsNewSession: true,
      experimentCompleted: false,
      configInfo: {
        name: selectedConfig.name,
        description: selectedConfig.description || selectedConfig.name,
      },
    };
  };

  const getExperimentProgress = () => {
    const completed = usedConfigs.length;
    const remaining = CONFIG_KEYS.length - completed;

    return {
      phase: experimentPhase,
      totalConfigs: CONFIG_KEYS.length,
      completed,
      remaining,
      usedConfigs: [...usedConfigs],
      currentConfig,
      currentMachine,
      progress: Math.round((completed / CONFIG_KEYS.length) * 100),
    };
  };

  const getCurrentMachineInfo = () => {
    if (!currentMachine || !currentConfig || !machineConfig) return null;

    const config = machineConfig.configs[currentConfig];
    return {
      configKey: currentConfig,
      configName: config?.name || "Unknown",
      machineId: currentMachine.id,
      machineIp: currentMachine.public_ip || currentMachine.api_base_url,
      apiBaseUrl,
    };
  };

  const incrementBaselineMessages = () => {
    if (experimentPhase === "baseline") {
      setBaselineMessageCount((previous) => previous + 1);
    }
    setCurrentChatMessageCount((previous) => previous + 1);
  };

  const resetCurrentChatMessages = () => {
    setCurrentChatMessageCount(0);
  };

  const toggleTestMode = () => {
    setIsTestMode((previous) => !previous);
  };

  const generateMockResponse = (message, config) => {
    const descriptions = {
      a: "ClueCollector plus adaptation",
      b: "ClueCollector only",
      c: "adaptation only",
      d: "baseline",
      e: "raw model",
    };

    return `**Mock ${config?.toUpperCase()} response (${descriptions[config] || "unknown"})**

The UI is running in local preview mode for the query: "${message}".

1. Confirm the user-visible symptom.
2. Collect or inspect the relevant context.
3. Provide the next action adapted to the active condition.`;
  };

  const testMachineConnection = async (machineOrUrl) => {
    const endpoint = machineOrUrl?.startsWith("http")
      ? machineOrUrl
      : `http://${machineOrUrl}:5000`;

    try {
      setConnectionStatus("unknown");
      const response = await fetch(`${endpoint}/health`, { method: "GET" });
      setConnectionStatus(response.ok ? "connected" : "failed");
      return response.ok;
    } catch {
      setConnectionStatus("failed");
      return false;
    }
  };

  const testMachineConnectionMock = async (machineOrUrl, config) => {
    if (!isTestMode) {
      return testMachineConnection(machineOrUrl);
    }

    const logEntry = {
      timestamp: new Date().toISOString(),
      target: machineOrUrl,
      config,
      status: "mocked_success",
    };

    setTestModeConnectionLog((previous) => [...previous, logEntry]);
    setConnectionStatus("connected");
    return true;
  };

  const beginExperimentSafely = async () => {
    if (baselineMessageCount === 0) {
      setTransitionError(
        "Please send at least one message in baseline mode before starting the experiment."
      );
      return false;
    }

    setIsTransitioning(true);
    setTransitionError(null);
    beginExperiment();
    setIsTransitioning(false);
    return true;
  };

  const selectFirstExperimentConfigSafely = async () => {
    setIsTransitioning(true);
    setTransitionError(null);

    const result = selectFirstExperimentConfig();
    if (!result) {
      setTransitionError("Machine configuration is not loaded.");
      setIsTransitioning(false);
      return null;
    }

    const connected = await testMachineConnectionMock(
      result.apiBaseUrl,
      result.config
    );
    setIsTransitioning(false);
    return connected ? result : null;
  };

  const selectNextConfigSafely = async () => {
    setIsTransitioning(true);
    setTransitionError(null);

    const result = selectNextConfig();
    if (!result || result.experimentCompleted) {
      setIsTransitioning(false);
      return result;
    }

    const connected = await testMachineConnectionMock(
      result.apiBaseUrl,
      result.config
    );
    setIsTransitioning(false);
    return connected ? result : null;
  };

  const clearTransitionError = () => {
    setTransitionError(null);
  };

  const resetExperiment = () => {
    setUsedConfigs([]);
    setTotalConversations(0);
    setExperimentStartTime(null);
    setExperimentPhase("baseline");
    setBaselineMessageCount(0);
    setCurrentChatMessageCount(0);
    setIsTransitioning(false);
    setConnectionStatus("unknown");
    setTransitionError(null);
    setTestModeConnectionLog([]);
    setIsReconnecting(false);
    setCurrentMachine(null);
    selectBaselineMachine();
  };

  const reconnectToCurrentConfig = async () => {
    if (!machineConfig || !currentConfig) {
      return { success: false, error: "No current configuration is active." };
    }

    const configInfo = machineConfig.configs[currentConfig];
    if (!configInfo?.instances || configInfo.instances.length < 2) {
      return { success: false, error: "No alternate preview server configured." };
    }

    setIsReconnecting(true);
    const newMachineIndex = currentMachineIndex === 0 ? 1 : 0;
    const alternateMachine = configInfo.instances[newMachineIndex];
    const alternateApiBaseUrl = getMachineApiBaseUrl(alternateMachine);
    const connected = await testMachineConnectionMock(
      alternateApiBaseUrl,
      currentConfig
    );

    if (connected) {
      setCurrentMachine(alternateMachine);
      setCurrentMachineIndex(newMachineIndex);
      setApiBaseUrl(alternateApiBaseUrl);
      setIsReconnecting(false);
      return {
        success: true,
        machine: alternateMachine,
        apiBaseUrl: alternateApiBaseUrl,
        needsNewSession: true,
        message: `Reconnected to ${configInfo.name} (${alternateMachine.id})`,
      };
    }

    setIsReconnecting(false);
    return { success: false, error: "Connection check failed." };
  };

  return {
    experimentPhase,
    currentConfig,
    currentMachine,
    usedConfigs,
    apiBaseUrl,
    totalConversations,
    configLoading,
    configError,
    baselineMessageCount,
    currentChatMessageCount,
    isTransitioning,
    connectionStatus,
    transitionError,
    isTestMode,
    testModeConnectionLog,
    beginExperiment,
    selectFirstExperimentConfig,
    selectNextConfig,
    beginExperimentSafely,
    selectFirstExperimentConfigSafely,
    selectNextConfigSafely,
    incrementBaselineMessages,
    resetCurrentChatMessages,
    clearTransitionError,
    resetExperiment,
    retryConfigLoad: loadMachineConfig,
    testMachineConnection,
    toggleTestMode,
    generateMockResponse,
    testMachineConnectionMock,
    reconnectToCurrentConfig,
    getExperimentProgress,
    getCurrentMachineInfo,
    isBaseline: experimentPhase === "baseline",
    isExperiment: experimentPhase === "experiment",
    isCompleted: experimentPhase === "completed",
    canBeginExperiment:
      experimentPhase === "baseline" &&
      !configLoading &&
      !configError &&
      baselineMessageCount > 0 &&
      !isTransitioning,
    canStartNewChat: currentChatMessageCount > 0 && !isTransitioning,
    isReady: !configLoading && !configError && machineConfig !== null,
    isReconnecting,
    currentMachineIndex,
  };
};
